services:
  neo4j:
    # image: neo4j:4.4-enterprise
    build: ./neo4j/
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/adminadmin
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=false
      - apoc.initializer.cypher.1=CALL apoc.cypher.runSchemaFile("file:////scripts/schema.cypher")
      - apoc.initializer.cypher.2=CALL apoc.cypher.runFile("file:////scripts/init.cypher")
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_PLUGINS=["apoc", "n10s"]

  streamlit:
    build:
      context: ./streamlit
    entrypoint: streamlit run main.py --server.port=8501 --server.address=0.0.0.0
    ports:
     - "8501:8501"
    env_file:
      - ./.env